[workspace]
members = [
    "nix-wasm-rust",
    "nix-wasm-plugin-fib",
    "nix-wasm-plugin-ini",
    "nix-wasm-plugin-yaml",
    "nix-wasm-plugin-mandelbrot",
    "nix-wasm-plugin-test",
]
resolver = "2"

[profile.release]
lto = true
opt-level = 's'
